# configuration for https://ohi-science.nceas.ucsb.edu/col
study_area:       Colombia
git_owner:        OHI-Science
git_repo:         col
git_slug:         OHI-Science/col
git_url:          https://github.com/OHI-Science/col
app_url:          http://ohi-science.nceas.ucsb.edu/col
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-11-18
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: 951a458152b7b891978d42d79d8292f4558829ff

tabs_hide:        
- Calculate
- Report

